name: bw_sponsor_preferential
description: 优惠和赞助模块
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  oktoast: ^2.3.1+1
  provider: ^4.0.4
  pull_to_refresh: ^1.5.7
  json_annotation: ^3.0.1
  cached_network_image: ^2.0.0

  biz_app_init:
    git:
      url: http://47.52.134.206/bw-flutter/biz_app_init.git
      ref: feature_v0.1
  bw_utils:
    git:
      url: http://47.52.134.206/bw-flutter/bw_utils.git
      ref: feature_v0.1
  biz_network_main:
    git:
      url: http://47.52.134.206/bw-flutter/biz_network_main.git
      ref: feature_v0.1

  bw_res:
    git:
      url: http://47.52.134.206/bw-flutter/bw_resources.git
      ref: feature_v0.1
      path: "packages/bw_res"

  biz_login:
    git:
      url: http://47.52.134.206/bw-flutter/biz_login.git
      ref: feature_v0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.4
  json_serializable: ^3.2.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
